version: '3'
services:
  maintain:
    image: "polyswarm/polyswarm-client"
    depends_on:
      - polyswarmd
    environment:
      - PYTHONUNBUFFERED=1
      - KEYFILE=docker/ambassador_keyfile
      - PASSWORD=password
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "balancemanager"
      - "maintain"
      - "--polyswarmd-addr"
      - "polyswarmd:31337"
      - "--insecure-transport"
      - "--testing"
      - "10"
      - "--maximum"
      - "105"
      - "--withdraw-target"
      - "101"
      - "100"
      - "12"
  deposit:
    image: "polyswarm/polyswarm-client"
    depends_on:
      - polyswarmd
    environment:
      - PYTHONUNBUFFERED=1
      - KEYFILE=docker/ambassador_keyfile
      - PASSWORD=password
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "balancemanager"
      - "withdraw"
      - "--polyswarmd-addr"
      - "polyswarmd:31337"
      - "--insecure-transport"
      - "--testing"
      - "10"
      - "10"
