version: '3'
services:
    polyswarmd:
        image: "polyswarm/polyswarmd"
        depends_on:
            - homechain
            - sidechain
            - contracts
            - consul
            - ipfs
        environment:
            - PYTHONUNBUFFERED=1
            - CONSUL=http://consul:8500
            - POLY_SIDECHAIN_NAME=gamma
        ports:
            - "31337:31337"
        networks:
            - polyswarmd
            - ipfs
            - consul
            - homechain
            - sidechain
    consul:
        image: "consul"
        ports:
            - "8500:8500"
        networks:
            - consul
    contracts:
        depends_on:
            - homechain
            - sidechain
        image: "polyswarm/contracts"
        environment:
            - geth=homechain
            - HOME_CHAIN=http://homechain:8545
            - SIDE_CHAIN=http://sidechain:8545
            - CONSUL=http://consul:8500
            - IPFS=http://ipfs:5001
            - OPTIONS=/config/users.yml
            - POLYSWARMD_HOST=polyswarmd
            - POLYSWARMD_PORT=31337
            - POLY_SIDECHAIN_NAME=gamma
        volumes:
            - "./config:/config"
        command: ["./scripts/migrate_and_create_config.sh"]
        networks:
            - homechain
            - sidechain
            - consul
    homechain:
        image: "polyswarm/priv-testnet"
        entrypoint: /bin/sh
        logging:
            driver: none
        environment:
            - NETWORK_ID=1337
            - CHAIN_NAME=homechain
        command: ["run_geth.sh", "--cache", "128", "--syncmode", "fast", "--verbosity", "5", "--networkid", "1337", "--gasprice", "0", "--targetgaslimit", "94000000", "--nodiscover", "--rpc", "--rpcaddr", "0.0.0.0", "--rpcvhosts", "localhost,homechain", "--rpcapi", "eth,web3,personal,net", "--ws", "--wsaddr", "0.0.0.0", "--wsapi", "eth,web3,personal,net", "--wsorigins", "*", "--etherbase", "0x32fe67b633d8880f6356ccb688d11718f490a135", "--unlock", "0x32fe67b633d8880f6356ccb688d11718f490a135,0x31c99a06cabed34f97a78742225f4594d1d16677,0x6aae54b496479a25cacb63aa9dc1e578412ee68c,0x850a2f35553f8a79da068323cbc7c9e1842585d5,0xb8a26662fc7fa93e8d525f6e9d8c90fcdb467aa1,0x58b6cb03655999e2ff76072d8836051ac5ddcad7,0xe6cc4b147e3b1b59d2ac2f2f3784bbac1774bbf7,0x28fad0751f8f406d962d27b60a2a47ccceeb8096,0x87cb0b17cf9ebcb0447da7da55c703812813524b,0x0f57baedcf2c84383492d1ea700835ce2492c48a,4b1867c484871926109e3c47668d5c0938ca3527,d87e4662653042c5da11711542c11f2c8433612d,4f10166cafd7856ea946124927d4478fdd18d979,f0243d9b2e332d7072dd4b143a881b3f135f380c,f870491ea0f53f67846eecb57855284d8270284d,34e583cf9c1789c3141538eec77d9f0b8f7e89f2,2b813f079e7e3cf24eeb1ac5853bd6f9118a04ea,1215242c8f0eff0a4ac06ea3d73caa78279fb9bb,05328f171b8c1463eafdacca478d9ee6a1d923f8,085ba02c35555fecb8147820135fdfec10eed85a", "--password", "password.txt"]
        depends_on:
            - homechain-sealer
        networks:
            homechain:
                ipv4_address: 154.20.0.100
        ports:
            - 8545:8545
            - 8546:8546
    homechain-sealer:
        image: "polyswarm/priv-testnet"
        entrypoint: /bin/sh
        # logging:
        #     driver: none
        environment:
            - NETWORK_ID=1337
            - CHAIN_NAME=homechain
        command: ["run_geth.sh", "--cache", "128", "--syncmode", "fast", "--verbosity", "5", "--gasprice", "0", "--networkid", "1337", "--targetgaslimit", "94000000", "--nodekey", "nodekeys/homechain-sealer", "--nodiscover", "--etherbase", "0x58b6cb03655999e2ff76072d8836051ac5ddcad7", "--unlock", "0x58b6cb03655999e2ff76072d8836051ac5ddcad7", "--password", "password.txt", "--mine"]
        networks:
            homechain:
                ipv4_address: 154.20.0.101
    sidechain:
        image: "polyswarm/priv-testnet"
        entrypoint: /bin/sh
        # logging:
        #     driver: none
        environment:
            - NETWORK_ID=1338
            - CHAIN_NAME=sidechain
        command: ["run_geth.sh", "--cache", "128", "--syncmode", "fast", "--verbosity", "5", "--networkid", "1338", "--gasprice", "0", "--targetgaslimit", "94000000", "--nodiscover", "--rpc", "--rpcaddr", "0.0.0.0", "--rpcvhosts", "localhost,sidechain", "--rpcapi", "eth,web3,personal,net", "--ws", "--wsaddr", "0.0.0.0", "--wsapi", "eth,web3,personal,net", "--wsorigins", "*", "--etherbase", "0xb8a26662fc7fa93e8d525f6e9d8c90fcdb467aa1", "--unlock", "0x32fe67b633d8880f6356ccb688d11718f490a135,0x31c99a06cabed34f97a78742225f4594d1d16677,0x6aae54b496479a25cacb63aa9dc1e578412ee68c,0x850a2f35553f8a79da068323cbc7c9e1842585d5,0xb8a26662fc7fa93e8d525f6e9d8c90fcdb467aa1,0x58b6cb03655999e2ff76072d8836051ac5ddcad7,0xe6cc4b147e3b1b59d2ac2f2f3784bbac1774bbf7,0x28fad0751f8f406d962d27b60a2a47ccceeb8096,0x87cb0b17cf9ebcb0447da7da55c703812813524b,0x0f57baedcf2c84383492d1ea700835ce2492c48a,4b1867c484871926109e3c47668d5c0938ca3527,d87e4662653042c5da11711542c11f2c8433612d,4f10166cafd7856ea946124927d4478fdd18d979,f0243d9b2e332d7072dd4b143a881b3f135f380c,f870491ea0f53f67846eecb57855284d8270284d,34e583cf9c1789c3141538eec77d9f0b8f7e89f2,2b813f079e7e3cf24eeb1ac5853bd6f9118a04ea,1215242c8f0eff0a4ac06ea3d73caa78279fb9bb,05328f171b8c1463eafdacca478d9ee6a1d923f8,085ba02c35555fecb8147820135fdfec10eed85a", "--password", "password.txt"]
        depends_on:
            - sidechain-sealer0
            - sidechain-sealer1
            - sidechain-sealer2
        networks:
            sidechain:
                ipv4_address: 154.20.1.100
        ports:
            - 7545:8545
            - 7546:8546
    sidechain-sealer0:
        image: "polyswarm/priv-testnet"
        entrypoint: /bin/sh
        # logging:
        #     driver: none
        environment:
            - NETWORK_ID=1338
            - CHAIN_NAME=sidechain
        command: ["run_geth.sh", "--cache", "128", "--syncmode", "fast", "--verbosity", "5", "--networkid", "1338", "--gasprice", "0", "--targetgaslimit", "94000000", "--nodekey", "nodekeys/sidechain-sealer0", "--nodiscover", "--etherbase", "0x31c99a06cabed34f97a78742225f4594d1d16677", "--unlock", "0x31c99a06cabed34f97a78742225f4594d1d16677", "--password", "password.txt", "--mine"]
        networks:
            sidechain:
                ipv4_address: 154.20.1.101
    sidechain-sealer1:
        image: "polyswarm/priv-testnet"
        entrypoint: /bin/sh
        logging:
            driver: none
        environment:
            - NETWORK_ID=1338
            - CHAIN_NAME=sidechain
        command: ["run_geth.sh", "--cache", "128", "--syncmode", "fast", "--verbosity", "5", "--networkid", "1338", "--gasprice", "0", "--targetgaslimit", "94000000", "--nodekey", "nodekeys/sidechain-sealer1", "--nodiscover", "--etherbase", "0x6aae54b496479a25cacb63aa9dc1e578412ee68c", "--unlock", "0x6aae54b496479a25cacb63aa9dc1e578412ee68c", "--password", "password.txt", "--mine"]
        networks:
            sidechain:
                ipv4_address: 154.20.1.102
    sidechain-sealer2:
        image: "polyswarm/priv-testnet"
        entrypoint: /bin/sh
        logging:
            driver: none
        environment:
            - NETWORK_ID=1338
            - CHAIN_NAME=sidechain
        command: ["run_geth.sh", "--cache", "128", "--syncmode", "fast", "--verbosity", "5", "--networkid", "1338", "--gasprice", "0", "--targetgaslimit", "94000000", "--nodekey", "nodekeys/sidechain-sealer2", "--nodiscover", "--etherbase", "0x850a2f35553f8a79da068323cbc7c9e1842585d5", "--unlock", "0x850a2f35553f8a79da068323cbc7c9e1842585d5", "--password", "password.txt", "--mine"]
        networks:
            sidechain:
                ipv4_address: 154.20.1.103
    ipfs:
        image: "ipfs/go-ipfs"
        environment:
            - IPFS_BIND_IP=0.0.0.0
        ports:
            - "4001:4001"
        volumes:
            - "ipfs-export:/export"
            - "ipfs-data:/data/ipfs"
        networks:
            ipfs:
volumes:
    ipfs-export:
    ipfs-data:
networks:
    homechain:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 154.20.0.0/24
    sidechain:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 154.20.1.0/24
    consul:
        driver: bridge
    ipfs:
        driver: bridge
    polyswarmd:
        driver: bridge
