version: '3'
services:
    polyswarmd:
        <<: &deploy_clause
          deploy:
            resources:
              reservations:
                memory: 512M
        image: "polyswarm/polyswarmd"
        depends_on:
            - homechain
            - ipfs
            - contracts
        environment:
            - PYTHONUNBUFFERED=1
            - CONSUL=http://consul:8500
            - POLY_SIDECHAIN_NAME=gamma
        ports:
            - "31337:31337"
    consul:
        <<: *deploy_clause
        image: "consul"
        logging:
            driver: none
        ports:
            - "8500:8500"
    contracts:
        <<: *deploy_clause
        depends_on:
            - homechain
            - sidechain
        image: "polyswarm/contracts"
        environment:
            - geth=homechain
            - HOME_CHAIN=http://homechain:8545
            - SIDE_CHAIN=http://sidechain:8545
            - CONSUL=http://consul:8500
            - IPFS=http://ipfs:5001
            - OPTIONS=/config/users.yml
            - POLYSWARMD_HOST=polyswarmd
            - POLYSWARMD_PORT=31337
            - POLY_SIDECHAIN_NAME=gamma
        volumes:
            - "./config:/config"
        command: ["./scripts/migrate_and_create_config.sh"]
    homechain:
        <<: *deploy_clause
        image: "polyswarm/priv-testnet"
        entrypoint: /bin/sh
        environment:
            - NETWORK_ID=1337
            - CHAIN_NAME=homechain
        # logging:
        #     driver: none
        ports:
            - "30303:30303"
            - "8545:8545"
        command: ["run_geth.sh", "--nodiscover", "--maxpeers", "0", "--syncmode", "full", "--targetgaslimit", "94000000", "--rpc", "--rpcaddr", "0.0.0.0", "--rpcapi", "eth,web3,personal,net", "--rpcvhosts", "*", "--ws", "--wsaddr", "127.0.0.1", "--wsapi", "eth,web3,personal,net", "--wsorigins", "*", "--etherbase", "0x34e583cf9c1789c3141538eec77d9f0b8f7e89f2", "--unlock", "4b1867c484871926109e3c47668d5c0938ca3527,d87e4662653042c5da11711542c11f2c8433612d,4f10166cafd7856ea946124927d4478fdd18d979,f0243d9b2e332d7072dd4b143a881b3f135f380c,f870491ea0f53f67846eecb57855284d8270284d,34e583cf9c1789c3141538eec77d9f0b8f7e89f2,2b813f079e7e3cf24eeb1ac5853bd6f9118a04ea,1215242c8f0eff0a4ac06ea3d73caa78279fb9bb,05328f171b8c1463eafdacca478d9ee6a1d923f8,085ba02c35555fecb8147820135fdfec10eed85a", "--password", "password.txt", "--mine", "--verbosity", "4"]
    sidechain:
        <<: *deploy_clause
        image: "polyswarm/priv-testnet"
        entrypoint: /bin/sh
        environment:
            - NETWORK_ID=1338
            - CHAIN_NAME=sidechain
        # logging:
        #     driver: none
        ports:
            - "30304:30303"
            - "7545:8545"
        command: ["run_geth.sh", "--nodiscover", "--maxpeers", "0", "--syncmode", "full", "--targetgaslimit", "94000000", "--rpc", "--rpcaddr", "0.0.0.0", "--rpcapi", "eth,web3,personal,net", "--rpcvhosts", "*", "--ws", "--wsaddr", "127.0.0.1", "--wsapi", "eth,web3,personal,net", "--wsorigins", "*", "--etherbase", "0x34e583cf9c1789c3141538eec77d9f0b8f7e89f2", "--unlock", "4b1867c484871926109e3c47668d5c0938ca3527,d87e4662653042c5da11711542c11f2c8433612d,4f10166cafd7856ea946124927d4478fdd18d979,f0243d9b2e332d7072dd4b143a881b3f135f380c,f870491ea0f53f67846eecb57855284d8270284d,34e583cf9c1789c3141538eec77d9f0b8f7e89f2,2b813f079e7e3cf24eeb1ac5853bd6f9118a04ea,1215242c8f0eff0a4ac06ea3d73caa78279fb9bb,05328f171b8c1463eafdacca478d9ee6a1d923f8,085ba02c35555fecb8147820135fdfec10eed85a", "--password", "password.txt", "--mine", "--verbosity", "4"]
    ipfs:
        <<: *deploy_clause
        image: "ipfs/go-ipfs"
        environment:
            - IPFS_BIND_IP=0.0.0.0
        ports:
            - "4001:4001"
        volumes:
            - "ipfs-export:/export"
            - "ipfs-data:/data/ipfs"
    relay0:
        <<: *deploy_clause
        image: "polyswarm/relay"
        depends_on:
            - homechain
            - sidechain
            - contracts
            - consul
        environment:
            - RELAY_ACCOUNT=0x1215242c8f0eff0a4ac06ea3d73caa78279fb9bb
            - RELAY_PASSWORD=password
            - RUST_LOG=polyswarm_relay=trace
            - POLY_SIDECHAIN_NAME=gamma
            - CONSUL=http://consul:8500
    relay1:
        <<: *deploy_clause
        image: "polyswarm/relay"
        depends_on:
            - homechain
            - sidechain
            - contracts
            - consul
        environment:
            - RELAY_ACCOUNT=0x05328f171b8c1463eafdacca478d9ee6a1d923f8
            - RELAY_PASSWORD=password
            - RUST_LOG=polyswarm_relay=trace
            - POLY_SIDECHAIN_NAME=gamma
            - CONSUL=http://consul:8500
    relay2:
        <<: *deploy_clause
        image: "polyswarm/relay"
        depends_on:
            - homechain
            - sidechain
            - contracts
            - consul
        environment:
            - RELAY_ACCOUNT=0x085ba02c35555fecb8147820135fdfec10eed85a
            - RELAY_PASSWORD=password
            - RUST_LOG=polyswarm_relay=trace
            - POLY_SIDECHAIN_NAME=gamma
            - CONSUL=http://consul:8500
volumes:
    ipfs-export:
    ipfs-data:
