version: '2'
services:
  consumer_frontend:
    image: "polyswarm/consumer"
    ports:
      - "12322:12322"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_ADDR=redis:6379
      - KEYFILE=docker/consumer_keyfile
    command:
      - "dockerize"
      - "-wait"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "tcp://redis:6379"
      - "-timeout"
      - "1000s"
      - "consumer"
      - "frontend"
      - "--polyswarmd-addr"
      - "polyswarmd:31337"
      - "--insecure-transport"
  consumer_backend:
    image: "polyswarm/consumer"
    environment:
      - PYTHONUNBUFFERED=1
      - KEYFILE=docker/consumer_keyfile
      - PASSWORD=password
      - CHAIN=home
      - REDIS_ADDR=redis:6379
    command:
      - "dockerize"
      - "-wait"
      - "tcp://redis:6379"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "consumer"
      - "backend"
      - "--polyswarmd-addr"
      - "polyswarmd:31337"
      - "--insecure-transport"
  redis:
    image: "redis"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
