version: '3'
services:
  ambassador:
    image: "polyswarm/ambassador"
    depends_on:
      - polyswarmd
    environment:
      - ADDRESS=0x4b1867c484871926109e3c47668d5c0938ca3527
      - POLYSWARMD_HOST=polyswarmd:31337
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "python"
      - "ambassador.py"
      - "--testing"
      - "10"
  arbiter:
    image: "polyswarm/polyswarm-client"
    depends_on:
      - polyswarmd
    environment:
      - PYTHONUNBUFFERED=1
      - KEYFILE=docker/arbiter_keyfile
      - PASSWORD=password
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "arbiter"
      - "--polyswarmd-addr"
      - "polyswarmd:31337"
      - "--insecure-transport"
      - "--testing"
      - "10"
      - "--backend"
      - "verbatim"
  microengine:
    image: "polyswarm/microengine"
    depends_on:
      - polyswarmd
    environment:
      - ADDRESS=0x05328f171b8c1463eaFDACCA478D9EE6a1d923F8
      - POLYSWARMD_HOST=polyswarmd
      - POLYSWARMD_PORT=31337
      - POLYSWARMD_ADDR=http://polyswarmd:31337
      - CLAMD_HOST=clamav
      - CLAMD_PORT=3310
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "microengine"
      - "--keyfile"
      - "docker/keyfile"
      - "--password"
      - "password"
      - "--backend"
      - "eicar"
